function(a) {

			ok(false, 'テスト失敗。initPromiseがresolve()された');

		}