function(context) {

						ok(false, 'テスト失敗。__initが実行された');

					}