function(exception) {
        self.emit("netError", exception);
    }